name: cd

on: 
  push:
    branches:
      - release

jobs:
  build:
    # runs-on: self-hosted-cmi
    runs-on: windows-2019
    name: build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    
    - name: Restore Packages
      run: nuget restore Ws_OLS_FEL.sln
    
    - name: Build solution
      run: msbuild Ws_OLS_FEL.sln -t:rebuild -property:Configuration=Release

  DeployTest:
    environment: testing
    env:
      IP_DEPLOY: ${{secrets.IP_DEPLOY}}
      USERNAME_DEPLOY: ${{secrets.USERNAME_DEPLOY}}
      PASSWORD_DEPLOY: ${{secrets.PASSWORD_DEPLOY}}
      BASE: ${{vars.BASE}}
      DIRECTORYDESTINY: ${{vars.DIRECTORYDESTINY}}
    needs: build
    runs-on: self-hosted-cmi
    name: deploytest
    steps:
      - uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist-files
      - name: Output contents
        shell: powershell
        run: |
          $ORIGIN = "dist-files"
          ./updateconfig.ps1 "$($ORIGIN)/ServBoHExtInventarioTrasladoSS.dll.config" ${{vars.URLAPICOLAS}} ${{vars.APICONEXIONDB}} ${{vars.NOMBRESERVICIO}} ${{vars.SERVICIODESTINO}} ${{vars.CONEXIONDB}} ${{vars.CONEXIONDB2}} ${{vars.CORREO}} ${{vars.IDMENU}} ${{vars.AMBIENTE}} ${{vars.DIRECTORIOBITACORAERRORES}}
          ./deploy.ps1 ${{ env.IP_DEPLOY }} $ORIGIN ${{env.USERNAME_DEPLOY}} ${{env.PASSWORD_DEPLOY}} ${{ env.BASE }} ${{ env.DIRECTORYDESTINY }} 
    
  DeployProd:
    environment: production
    env:
      IP_DEPLOY: ${{secrets.IP_DEPLOY}}
      USERNAME_DEPLOY: ${{secrets.USERNAME_DEPLOY}}
      PASSWORD_DEPLOY: ${{secrets.PASSWORD_DEPLOY}}
      BASE: ${{vars.BASE}}
      DIRECTORYDESTINY: ${{vars.DIRECTORYDESTINY}}
    needs: DeployTest
    runs-on: self-hosted-cmi
    name: deployprod
    steps:
      - uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist-files
      - name: Output contents
        shell: powershell
        run: |
          $ORIGIN = "dist-files"
          ./updateconfig.ps1 "$($ORIGIN)/ServBoHExtInventarioTrasladoSS.dll.config" ${{vars.URLAPICOLAS}} ${{vars.APICONEXIONDB}} ${{vars.NOMBRESERVICIO}} ${{vars.SERVICIODESTINO}} ${{vars.CONEXIONDB}} ${{vars.CONEXIONDB2}} ${{vars.CORREO}} ${{vars.IDMENU}} ${{vars.AMBIENTE}} ${{vars.DIRECTORIOBITACORAERRORES}}
          ./deploy.ps1 ${{ env.IP_DEPLOY }} $ORIGIN ${{env.USERNAME_DEPLOY}} ${{env.PASSWORD_DEPLOY}} ${{ env.BASE }} ${{ env.DIRECTORYDESTINY }}  
