name: Build and SonarQube Analysis

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up .NET Framework
      run: |
        choco install dotnetfx --version=4.5.0 -y
        
    - name: Restore NuGet packages
      run: nuget restore Ws_OLS_FEL.sln

    - name: Build Solution
      run: |
        $msbuildPath = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
        $env:Path += ";$msbuildPath"
        msbuild /p:Configuration=Release /p:Platform="Any CPU" Ws_OLS_FEL.sln

    - name: Run Tests
      run: |
        dotnet test Ws_OLS_FEL.sln --configuration Release

    - name: Cache SonarQube packages
      uses: actions/cache@v1
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache SonarQube scanner
      id: cache-sonar-scanner
      uses: actions/cache@v1
      with:
        path: .\.sonar\scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner

    - name: Install SonarQube scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        New-Item -Path .\.sonar\scanner -ItemType Directory
        dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

    - name: Build and analyze
      shell: powershell
      run: |
        .\.sonar\scanner\dotnet-sonarscanner begin /k:"CMI.Ws_OLS_FEL" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
        dotnet build
        .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
